<?php

namespace Database\Seeders;

use App\Models\CarBrand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CarBrandsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brands = [
            ['name' => 'Acura', 'slug' => Str::slug('Acura'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Alfa Romeo', 'slug' => Str::slug('Alfa Romeo'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Aston Martin', 'slug' => Str::slug('Aston Martin'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Audi', 'slug' => Str::slug('Audi'), 'is_featured' => '1', 'logo' => 'frontAssets/img/brand/audi.png'],
            ['name' => 'Bentley', 'slug' => Str::slug('Bentley'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'BMW', 'slug' => Str::slug('BMW'), 'is_featured' => '1', 'logo' => 'frontAssets/img/brand/bmw.png'],
            ['name' => 'Bugatti', 'slug' => Str::slug('Bugatti'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Buick', 'slug' => Str::slug('Buick'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'BYD', 'slug' => Str::slug('BYD'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Cadillac', 'slug' => Str::slug('Cadillac'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Changan', 'slug' => Str::slug('Changan'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Chery', 'slug' => Str::slug('Chery'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Chevrolet', 'slug' => Str::slug('Chevrolet'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Chrysler', 'slug' => Str::slug('Chrysler'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Citroën', 'slug' => Str::slug('Citroën'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Dacia', 'slug' => Str::slug('Dacia'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Daewoo', 'slug' => Str::slug('Daewoo'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Daihatsu', 'slug' => Str::slug('Daihatsu'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Dodge', 'slug' => Str::slug('Dodge'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Dongfeng', 'slug' => Str::slug('Dongfeng'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'DS Automobiles', 'slug' => Str::slug('DS Automobiles'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'FAW', 'slug' => Str::slug('FAW'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Ferrari', 'slug' => Str::slug('Ferrari'), 'is_featured' => '1', 'logo' => 'frontAssets/img/brand/ferrari.png'],
            ['name' => 'Fiat', 'slug' => Str::slug('Fiat'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Fisker', 'slug' => Str::slug('Fisker'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Ford', 'slug' => Str::slug('Ford'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Geely', 'slug' => Str::slug('Geely'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Genesis', 'slug' => Str::slug('Genesis'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'GMC', 'slug' => Str::slug('GMC'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Great Wall', 'slug' => Str::slug('Great Wall'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Haval', 'slug' => Str::slug('Haval'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Hino', 'slug' => Str::slug('Hino'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Honda', 'slug' => Str::slug('Honda'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Hyundai', 'slug' => Str::slug('Hyundai'), 'is_featured' => '1', 'logo' => 'frontAssets/img/brand/hundyi.png'],
            ['name' => 'Infiniti', 'slug' => Str::slug('Infiniti'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Isuzu', 'slug' => Str::slug('Isuzu'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Jaguar', 'slug' => Str::slug('Jaguar'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Jeep', 'slug' => Str::slug('Jeep'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Kia', 'slug' => Str::slug('Kia'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Koenigsegg', 'slug' => Str::slug('Koenigsegg'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Lada', 'slug' => Str::slug('Lada'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Lamborghini', 'slug' => Str::slug('Lamborghini'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Lancia', 'slug' => Str::slug('Lancia'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Land Rover', 'slug' => Str::slug('Land Rover'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Lexus', 'slug' => Str::slug('Lexus'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Lincoln', 'slug' => Str::slug('Lincoln'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Lotus', 'slug' => Str::slug('Lotus'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Lucid', 'slug' => Str::slug('Lucid'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Mahindra', 'slug' => Str::slug('Mahindra'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Maserati', 'slug' => Str::slug('Maserati'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Maybach', 'slug' => Str::slug('Maybach'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Mazda', 'slug' => Str::slug('Mazda'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'McLaren', 'slug' => Str::slug('McLaren'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Mercedes-Benz', 'slug' => Str::slug('Mercedes-Benz'), 'is_featured' => '1', 'logo' => 'frontAssets/img/brand/mercedes.png'],
            ['name' => 'MG', 'slug' => Str::slug('MG'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Mini', 'slug' => Str::slug('Mini'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Mitsubishi', 'slug' => Str::slug('Mitsubishi'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Nissan', 'slug' => Str::slug('Nissan'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Opel', 'slug' => Str::slug('Opel'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Pagani', 'slug' => Str::slug('Pagani'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Peugeot', 'slug' => Str::slug('Peugeot'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Polestar', 'slug' => Str::slug('Polestar'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Pontiac', 'slug' => Str::slug('Pontiac'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Porsche', 'slug' => Str::slug('Porsche'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Proton', 'slug' => Str::slug('Proton'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Ram', 'slug' => Str::slug('Ram'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Renault', 'slug' => Str::slug('Renault'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Rivian', 'slug' => Str::slug('Rivian'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Rolls-Royce', 'slug' => Str::slug('Rolls-Royce'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Saab', 'slug' => Str::slug('Saab'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Samsung', 'slug' => Str::slug('Samsung'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Saturn', 'slug' => Str::slug('Saturn'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Tesla', 'slug' => Str::slug('Tesla'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Toyota', 'slug' => Str::slug('Toyota'), 'is_featured' => '1', 'logo' => 'frontAssets/img/brand/toyota.png'],
            ['name' => 'Volkswagen', 'slug' => Str::slug('Volkswagen'), 'is_featured' => '0', 'logo' => null],
            ['name' => 'Volvo', 'slug' => Str::slug('Volvo'), 'is_featured' => '0', 'logo' => null],
        ];

        foreach ($brands as $brand) {
            CarBrand::create($brand);
        }


        // $brands = [
        //     'Acura',
        //     'Alfa Romeo',
        //     'Aston Martin',
        //     'Audi',
        //     'Bentley',
        //     'BMW',
        //     'Bugatti',
        //     'Buick',
        //     'BYD',
        //     'Cadillac',
        //     'Changan',
        //     'Chery',
        //     'Chevrolet',
        //     'Chrysler',
        //     'Citroën',
        //     'Dacia',
        //     'Daewoo',
        //     'Daihatsu',
        //     'Dodge',
        //     'Dongfeng',
        //     'DS Automobiles',
        //     'FAW',
        //     'Ferrari',
        //     'Fiat',
        //     'Fisker',
        //     'Ford',
        //     'Geely',
        //     'Genesis',
        //     'GMC',
        //     'Great Wall',
        //     'Haval',
        //     'Hino',
        //     'Honda',
        //     'Hyundai',
        //     'Infiniti',
        //     'Isuzu',
        //     'Jaguar',
        //     'Jeep',
        //     'Kia',
        //     'Koenigsegg',
        //     'Lada',
        //     'Lamborghini',
        //     'Lancia',
        //     'Land Rover',
        //     'Lexus',
        //     'Lincoln',
        //     'Lotus',
        //     'Lucid',
        //     'Mahindra',
        //     'Maserati',
        //     'Maybach',
        //     'Mazda',
        //     'McLaren',
        //     'Mercedes-Benz',
        //     'MG',
        //     'Mini',
        //     'Mitsubishi',
        //     'Nissan',
        //     'Opel',
        //     'Pagani',
        //     'Peugeot',
        //     'Polestar',
        //     'Pontiac',
        //     'Porsche',
        //     'Proton',
        //     'RAM',
        //     'Renault',
        //     'Rivian',
        //     'Rolls-Royce',
        //     'Rover',
        //     'Saab',
        //     'Scion',
        //     'SEAT',
        //     'Škoda',
        //     'Smart',
        //     'SsangYong',
        //     'Subaru',
        //     'Suzuki',
        //     'Tata',
        //     'Tesla',
        //     'Toyota',
        //     'Vauxhall',
        //     'VinFast',
        //     'Volkswagen',
        //     'Volvo',
        //     'Wuling',
        //     'Zotye'
        // ];

        // $featuredBrands = ['Audi', 'BMW', 'Toyota', 'Ferrari', 'Tesla', 'Mercedes-Benz', 'Hyundai'];

        // foreach ($brands as $brand) {
        //     CarBrand::create([
        //         'name' => $brand,
        //         'slug' => Str::slug($brand),
        //         'is_active' => 'active',
        //         'is_featured' => in_array($brand, $featuredBrands) ? '1' : '0',
        //     ]);
        // }
    }
}
